FROM ubuntu:20.04

ENV HOME /root
WORKDIR "$HOME"

#--------------#
# Localization #
#--------------#

RUN apt-get update && apt-get upgrade -y
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y tzdata
ENV TZ=Asia/Tokyo

RUN apt-get install -y locales fonts-takao && locale-gen ja_JP.UTF-8
ENV LANG=ja_JP.UTF-8
ENV LANGUAGE=ja_JP:ja
ENV LC_ALL=ja_JP.UTF-8
RUN localedef -f UTF-8 -i ja_JP ja_JP.utf8

#-----------#
# Dev Tools #
#-----------#

# Install CMake 3.21.6 for g2o
# CLion supports CMake 2.8.11~3.21.x
RUN apt-get update && \
      apt-get install -y git build-essential libssl-dev
RUN git clone https://gitlab.kitware.com/cmake/cmake.git -b v3.21.6
RUN mkdir "$HOME/cmake/build"
WORKDIR "$HOME/cmake/build"
RUN ../bootstrap && make -j"$(nproc)" && make install
WORKDIR "$HOME"

RUN apt-get update && \
      apt-get install -y \
      gcc g++ gdb clang make \
      ninja-build autoconf automake \
      locales-all dos2unix rsync tar
RUN apt-get update && \
      apt-get install -y python3.8 python3-pip

#---------------#
# Source Builds #
#---------------#

# libboost-dev is not enough for PCL
RUN apt-get update && \
      apt-get install -y libboost-all-dev

# glog
RUN git clone https://github.com/google/glog.git -b v0.5.0
RUN mkdir "$HOME/glog/build"
WORKDIR "$HOME/glog/build"
RUN cmake .. && make -j"$(nproc)" && make install
WORKDIR "$HOME"
RUN rm -rf "$HOME/glog"

# gflags    
RUN git clone https://github.com/gflags/gflags.git -b v2.2.2
RUN mkdir "$HOME/gflags/build"
WORKDIR "$HOME/gflags/build"
RUN cmake .. && make -j"$(nproc)" && make install
WORKDIR "$HOME"
RUN rm -rf "$HOME/gflags"

# gtest
RUN git clone https://github.com/google/googletest.git -b release-1.11.0
RUN mkdir "$HOME/googletest/build"
WORKDIR "$HOME/googletest/build"
RUN cmake .. && make -j"$(nproc)" && make install
WORKDIR "$HOME"
RUN rm -rf "$HOME/googletest"

# Eigen
RUN git clone https://gitlab.com/libeigen/eigen.git -b 3.4.0
RUN mkdir "$HOME/eigen/build"
WORKDIR "$HOME/eigen/build"
RUN cmake .. && make -j"$(nproc)" && make install
WORKDIR "$HOME"
RUN rm -rf "$HOME/eigen"

# ceres-solver
RUN apt-get update && \
      apt-get install -y libatlas-base-dev libsuitesparse-dev
RUN git clone https://github.com/ceres-solver/ceres-solver.git -b 2.1.0
RUN mkdir "$HOME/ceres-solver/build"
WORKDIR "$HOME/ceres-solver/build"
RUN cmake .. && make -j"$(nproc)" && make install
WORKDIR "$HOME"
RUN rm -rf "$HOME/ceres-solver"

# g2o
RUN apt-get update && \
      apt-get install -y libsuitesparse-dev qtdeclarative5-dev qt5-qmake libqglviewer-dev-qt5
RUN git clone https://github.com/RainerKuemmerle/g2o.git -b 20230223_git
RUN mkdir "$HOME/g2o/build"
WORKDIR "$HOME/g2o/build"
RUN cmake .. && make -j"$(nproc)" && make install
WORKDIR "$HOME"
RUN rm -rf "$HOME/g2o"

# Sophus
RUN git clone https://github.com/strasdat/Sophus.git -b 1.22.10
RUN mkdir "$HOME/Sophus/build"
WORKDIR "$HOME/Sophus/build"
RUN cmake .. && make -j"$(nproc)" && make install
WORKDIR $HOME
RUN rm -rf "$HOME/Sophus"

# matplotlib-cpp
RUN apt-get update && \
      apt-get install -y python3-matplotlib python3-numpy python3-dev wget
RUN wget https://github.com/lava/matplotlib-cpp/raw/master/matplotlibcpp.h -P /usr/local/include

RUN apt-get install -y libopencv-dev

# PCL
# RUN apt-get install -y libusb-1.0-0-dev libflann-dev libvtk7-dev libpcap-dev
# RUN git clone https://github.com/PointCloudLibrary/pcl.git -b pcl-1.12.1
# RUN mkdir "$HOME/pcl/build"
# WORKDIR "$HOME/pcl/build"
# RUN cmake .. && make -j"$(nproc)" && make install
# WORKDIR "$HOME"
# RUN rm -rf "$HOME/pcl"
RUN apt-get update && \
      apt-get install -y libpcl-dev

# pybind11
RUN git clone https://github.com/pybind/pybind11.git -b v2.10.4
RUN mkdir "$HOME/pybind11/build"
WORKDIR "$HOME/pybind11/build"
RUN cmake .. && make -j"$(nproc)" && make install
WORKDIR "$HOME"
RUN rm -rf "$HOME/pybind11"

#--------------#
# gdb printers #
#--------------#

# for OpenCV Mat debugger
RUN apt-get update && \
      apt-get install -y python3-pip
RUN pip3 install numpy
# Place gdb scripts
COPY gdbinit.sh "$HOME/.gdbinit"
COPY gdb/ "$HOME/gdb/"

#-------------#
# Python libs #
#-------------#

# Pangolin
RUN apt-get update && \
      apt-get install -y libglew-dev libpython2.7-dev libeigen3-dev
# Bug fixed PR version
RUN git clone https://github.com/bravech/pangolin "$HOME/pangolin"
RUN mkdir "$HOME/pangolin/build"
WORKDIR "$HOME/pangolin/build"
RUN cmake .. && make -j"$(nproc)"
RUN sed -i "s/install_dirs/install_dir/g" "$HOME/pangolin/setup.py"
WORKDIR "$HOME/pangolin"
RUN python3 setup.py install
WORKDIR "$HOME"

# g2opy
RUN apt-get update && \
      apt-get install -y libsuitesparse-dev qtdeclarative5-dev libqglviewer-dev-qt5
# Bug fixed PR version
RUN git clone https://github.com/codegrafix/g2opy.git "$HOME/g2opy"
RUN mkdir "$HOME/g2opy/build"
WORKDIR "$HOME/g2opy/build"
RUN cmake .. && make -j"$(nproc)"
WORKDIR "$HOME/g2opy"
RUN python3 setup.py install
WORKDIR "$HOME"

COPY requirements.txt "$HOME"
RUN pip install -r requirements.txt

RUN apt-get clean && \ 
      rm -rf /var/lib/apt/lists/*

RUN mkdir /workspace
WORKDIR /workspace
